# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/OligoSeeker',
                'doc_host': 'https://mtinti.github.io',
                'git_url': 'https://github.com/mtinti/OligoSeeker',
                'lib_path': 'OligoSeeker'},
  'syms': {'OligoSeeker.core': {'OligoSeeker.core.foo': ('core.html#foo', 'OligoSeeker/core.py')}}}
